import { defineTargetSpecs } from "./builders.mts";

const SETTINGS_SCHEMA_NEEDLE = "preventSleepWhileRunning";
const GENERAL_SETTINGS_NEEDLE = "settings.general.power.preventSleepWhileRunning.description";

const SETTINGS_SCHEMA_GUARDED_SIGNATURE =
  /(preventSleepWhileRunning:([A-Za-z_$][\w$]*)\(\{agentAccess:`read-write`,default:!1,description:`Whether the machine stays awake while Codex is running`,key:`preventSleepWhileRunning`,schema:([A-Za-z_$][\w$]*)\}\),)/;
const SETTINGS_SCHEMA_PATCHED_SIGNATURE =
  /disableAutomaticUpdates:[A-Za-z_$][\w$]*\(\{agentAccess:`read-write`,default:!1,description:`Whether automatic update checks and forced installs are disabled`,key:`disableAutomaticUpdates`,schema:[A-Za-z_$][\w$]*\}\)/;

const GENERAL_SETTINGS_GUARDED_SIGNATURE =
  /function Kr\(\)\{let e=\(0,\$\.c\)\(10\),t=a\(s\),\{platform:n\}=Ee\(\),r=n!==`windows`,i=N\(\),o=z\(j\.preventSleepWhileRunning\);if\(!r\)return null;let c,l;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(c=\(0,Z\.jsx\)\(P,\{\.\.\.G\.preventSleepWhileRunning\}\),l=\(0,Z\.jsx\)\(P,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`\}\),e\[0\]=c,e\[1\]=l\):\(c=e\[0\],l=e\[1\]\);let u=o\?\?!1,d;e\[2\]===t\?d=e\[3\]:\(d=e=>\{B\(t,j\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=d\);let f;e\[4\]===i\?f=e\[5\]:\(f=i\.formatMessage\(G\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=f\);let p;return e\[6\]!==u\|\|e\[7\]!==d\|\|e\[8\]!==f\?\(p=\(0,Z\.jsx\)\(J,\{label:c,description:l,control:\(0,Z\.jsx\)\(q,\{checked:u,onChange:d,ariaLabel:f\}\)\}\),e\[6\]=u,e\[7\]=d,e\[8\]=f,e\[9\]=p\):p=e\[9\],p\}/;
const GENERAL_SETTINGS_PATCHED_SIGNATURE =
  /codexfastUpdateMessages[^]*?B\(t,j\.disableAutomaticUpdates,e\)/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26623 =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,i=([A-Za-z_$][\w$]*)\(\),a=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let o,s;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(o=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),s=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`\}\),e\[0\]=o,e\[1\]=s\):\(o=e\[0\],s=e\[1\]\);let c=a\?\?!1,l;e\[2\]===t\?l=e\[3\]:\(l=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=l\);let u;e\[4\]===i\?u=e\[5\]:\(u=i\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=u\);let d;return e\[6\]!==c\|\|e\[7\]!==l\|\|e\[8\]!==u\?\(d=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:o,description:s,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:c,onChange:l,ariaLabel:u\}\)\}\),e\[6\]=c,e\[7\]=l,e\[8\]=u,e\[9\]=d\):d=e\[9\],d\}/;
const GENERAL_SETTINGS_PATCHED_SIGNATURE_26623 =
  /codexfastUpdateMessages[^]*?[A-Za-z_$][\w$]*\(t,[A-Za-z_$][\w$]*\.disableAutomaticUpdates,e\)/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_LOCAL_COLLISION =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,i=([A-Za-z_$][\w$]*)\(\),a=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let o,s;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(o=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),s=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`\}\),e\[0\]=o,e\[1\]=s\):\(o=e\[0\],s=e\[1\]\);let u=a\?\?!1,d;e\[2\]===t\?d=e\[3\]:\(d=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=d\);let f;e\[4\]===i\?f=e\[5\]:\(f=i\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=f\);let p;return e\[6\]!==u\|\|e\[7\]!==d\|\|e\[8\]!==f\?\(p=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:o,description:s,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:u,onChange:d,ariaLabel:f\}\)\}\),e\[6\]=u,e\[7\]=d,e\[8\]=f,e\[9\]=p\):p=e\[9\],p\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_RENAMED_LOCALS =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,[A-Za-z_$][\w$]*=([A-Za-z_$][\w$]*)\(\),[A-Za-z_$][\w$]*=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let [A-Za-z_$][\w$]*,[A-Za-z_$][\w$]*;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\([A-Za-z_$][\w$]*=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),[A-Za-z_$][\w$]*=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`\}\),e\[0\]=[A-Za-z_$][\w$]*,e\[1\]=[A-Za-z_$][\w$]*\):\([A-Za-z_$][\w$]*=e\[0\],[A-Za-z_$][\w$]*=e\[1\]\);let [A-Za-z_$][\w$]*=[A-Za-z_$][\w$]*\?\?!1,[A-Za-z_$][\w$]*;e\[2\]===t\?[A-Za-z_$][\w$]*=e\[3\]:\([A-Za-z_$][\w$]*=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=[A-Za-z_$][\w$]*\);let [A-Za-z_$][\w$]*;e\[4\]===[A-Za-z_$][\w$]*\?[A-Za-z_$][\w$]*=e\[5\]:\([A-Za-z_$][\w$]*=[A-Za-z_$][\w$]*\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=[A-Za-z_$][\w$]*,e\[5\]=[A-Za-z_$][\w$]*\);let [A-Za-z_$][\w$]*;return e\[6\]!==[A-Za-z_$][\w$]*\|\|e\[7\]!==[A-Za-z_$][\w$]*\|\|e\[8\]!==[A-Za-z_$][\w$]*\?\([A-Za-z_$][\w$]*=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:[A-Za-z_$][\w$]*,description:[A-Za-z_$][\w$]*,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:[A-Za-z_$][\w$]*,onChange:[A-Za-z_$][\w$]*,ariaLabel:[A-Za-z_$][\w$]*\}\)\}\),e\[6\]=[A-Za-z_$][\w$]*,e\[7\]=[A-Za-z_$][\w$]*,e\[8\]=[A-Za-z_$][\w$]*,e\[9\]=[A-Za-z_$][\w$]*\):[A-Za-z_$][\w$]*=e\[9\],[A-Za-z_$][\w$]*\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_HOOKS =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),i=n!==`windows`,a=([A-Za-z_$][\w$]*)\(\),o=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!i\)return null;let s,c;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(s=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),c=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`\}\),e\[0\]=s,e\[1\]=c\):\(s=e\[0\],c=e\[1\]\);let l=o\?\?!1,u;e\[2\]===t\?u=e\[3\]:\(u=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=u\);let d;e\[4\]===a\?d=e\[5\]:\(d=a\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=a,e\[5\]=d\);let f;return e\[6\]!==l\|\|e\[7\]!==u\|\|e\[8\]!==d\?\(f=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:s,description:c,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:l,onChange:u,ariaLabel:d\}\)\}\),e\[6\]=l,e\[7\]=u,e\[8\]=d,e\[9\]=f\):f=e\[9\],f\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_APP_NAME =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,i=([A-Za-z_$][\w$]*)\(\),a=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let o;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(o=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),e\[0\]=o\):o=e\[0\];let s;e\[1\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(s=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while \{appName\} is running a task`,description:`Description for preventing sleep while a task runs`,values:\{appName:([A-Za-z_$][\w$]*)\}\}\),e\[1\]=s\):s=e\[1\];let c=a\?\?!1,l;e\[2\]===t\?l=e\[3\]:\(l=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=l\);let u;e\[4\]===i\?u=e\[5\]:\(u=i\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=u\);let d;return e\[6\]!==c\|\|e\[7\]!==l\|\|e\[8\]!==u\?\(d=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:o,description:s,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:c,onChange:l,ariaLabel:u\}\)\}\),e\[6\]=c,e\[7\]=l,e\[8\]=u,e\[9\]=d\):d=e\[9\],d\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_ROW_LOCAL_F =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,i=([A-Za-z_$][\w$]*)\(\),a=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let o;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(o=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),e\[0\]=o\):o=e\[0\];let s;e\[1\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(s=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while \{appName\} is running a task`,description:`Description for preventing sleep while a task runs`,values:\{appName:([A-Za-z_$][\w$]*)\}\}\),e\[1\]=s\):s=e\[1\];let c=a\?\?!1,l;e\[2\]===t\?l=e\[3\]:\(l=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=l\);let u;e\[4\]===i\?u=e\[5\]:\(u=i\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=u\);let f;return e\[6\]!==c\|\|e\[7\]!==l\|\|e\[8\]!==u\?\(f=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:o,description:s,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:c,onChange:l,ariaLabel:u\}\)\}\),e\[6\]=c,e\[7\]=l,e\[8\]=u,e\[9\]=f\):f=e\[9\],f\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_PLATFORM_LOCALS =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:r\}=([A-Za-z_$][\w$]*)\(\),i=r!==`windows`,a=([A-Za-z_$][\w$]*)\(\),o=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!i\)return null;let s;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(s=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),e\[0\]=s\):s=e\[0\];let c;e\[1\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(c=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while \{appName\} is running a task`,description:`Description for preventing sleep while a task runs`,values:\{appName:([A-Za-z_$][\w$]*)\}\}\),e\[1\]=c\):c=e\[1\];let l=o\?\?!1,u;e\[2\]===t\?u=e\[3\]:\(u=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=u\);let d;e\[4\]===a\?d=e\[5\]:\(d=a\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=a,e\[5\]=d\);let p;return e\[6\]!==l\|\|e\[7\]!==u\|\|e\[8\]!==d\?\(p=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:s,description:c,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:l,onChange:u,ariaLabel:d\}\)\}\),e\[6\]=l,e\[7\]=u,e\[8\]=d,e\[9\]=p\):p=e\[9\],p\}/;
const GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_SHIFTED_LOCALS =
  /function ([A-Za-z_$][\w$]*)\(\)\{let e=\(0,([A-Za-z_$][\w$]*)\.c\)\(10\),t=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\),\{platform:n\}=([A-Za-z_$][\w$]*)\(\),r=n!==`windows`,i=([A-Za-z_$][\w$]*)\(\),a=([A-Za-z_$][\w$]*)\(([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\);if\(!r\)return null;let o;e\[0\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(o=\(0,([A-Za-z_$][\w$]*)\.jsx\)\(([A-Za-z_$][\w$]*),\{\.\.\.([A-Za-z_$][\w$]*)\.preventSleepWhileRunning\}\),e\[0\]=o\):o=e\[0\];let s;e\[1\]===Symbol\.for\(`react\.memo_cache_sentinel`\)\?\(s=\(0,[A-Za-z_$][\w$]*\.jsx\)\([A-Za-z_$][\w$]*,\{id:`settings\.general\.power\.preventSleepWhileRunning\.description`,defaultMessage:`Keep your computer awake while \{appName\} is running a task`,description:`Description for preventing sleep while a task runs`,values:\{appName:([A-Za-z_$][\w$]*)\}\}\),e\[1\]=s\):s=e\[1\];let l=a\?\?!1,u;e\[2\]===t\?u=e\[3\]:\(u=e=>\{([A-Za-z_$][\w$]*)\(t,[A-Za-z_$][\w$]*\.preventSleepWhileRunning,e\)\},e\[2\]=t,e\[3\]=u\);let d;e\[4\]===i\?d=e\[5\]:\(d=i\.formatMessage\([A-Za-z_$][\w$]*\.preventSleepWhileRunning\),e\[4\]=i,e\[5\]=d\);let f;return e\[6\]!==l\|\|e\[7\]!==u\|\|e\[8\]!==d\?\(f=\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{label:o,description:s,control:\(0,[A-Za-z_$][\w$]*\.jsx\)\(([A-Za-z_$][\w$]*),\{checked:l,onChange:u,ariaLabel:d\}\)\}\),e\[6\]=l,e\[7\]=u,e\[8\]=d,e\[9\]=f\):f=e\[9\],f\}/;

const GENERAL_SETTINGS_REPLACEMENT = [
  "function Kr(){let e=(0,$.c)(17),t=a(s),{platform:n}=Ee(),r=n!==`windows`,i=N(),o=z(j.preventSleepWhileRunning),codexfastDisableAutomaticUpdates=z(j.disableAutomaticUpdates);if(!r)return null;let c,l;e[0]===Symbol.for(`react.memo_cache_sentinel`)?(c=(0,Z.jsx)(P,{...G.preventSleepWhileRunning}),l=(0,Z.jsx)(P,{id:`settings.general.power.preventSleepWhileRunning.description`,defaultMessage:`Keep your computer awake while Codex is running a chat`,description:`Description for preventing sleep while a chat runs`}),e[0]=c,e[1]=l):(c=e[0],l=e[1]);let u=o??!1,d;e[2]===t?d=e[3]:(d=e=>{B(t,j.preventSleepWhileRunning,e)},e[2]=t,e[3]=d);let f;e[4]===i?f=e[5]:(f=i.formatMessage(G.preventSleepWhileRunning),e[4]=i,e[5]=f);let p;e[6]!==u||e[7]!==d||e[8]!==f?(p=(0,Z.jsx)(J,{label:c,description:l,control:(0,Z.jsx)(q,{checked:u,onChange:d,ariaLabel:f})}),e[6]=u,e[7]=d,e[8]=f,e[9]=p):p=e[9];",
  "let codexfastUpdateLocale=(i.locale??globalThis.navigator?.language??``).toLowerCase(),codexfastUpdateMessages=codexfastUpdateLocale.startsWith(`zh-cn`)||codexfastUpdateLocale.startsWith(`zh-hans`)?{label:`停用自动更新`,description:`停止后续自动更新检查和安装，但不影响手动“检查更新”。`}:codexfastUpdateLocale.startsWith(`zh-tw`)||codexfastUpdateLocale.startsWith(`zh-hk`)||codexfastUpdateLocale.startsWith(`zh-hant`)?{label:`停用自動更新`,description:`停止後續自動更新檢查和安裝，但不影響手動「檢查更新」。`}:codexfastUpdateLocale.startsWith(`ja`)?{label:`自動更新を無効にする`,description:`今後の自動更新チェックとインストールを停止します。手動の「アップデートを確認」は無効になりません。`}:codexfastUpdateLocale.startsWith(`ko`)?{label:`자동 업데이트 비활성화`,description:`수동 업데이트 확인은 유지하면서 이후 자동 업데이트 확인 및 설치를 중지합니다.`}:codexfastUpdateLocale.startsWith(`fr`)?{label:`Désactiver les mises à jour automatiques`,description:`Arrête les prochaines recherches et installations automatiques sans désactiver la recherche manuelle.`}:codexfastUpdateLocale.startsWith(`de`)?{label:`Automatische Updates deaktivieren`,description:`Stoppt künftige automatische Prüfungen und Installationen, ohne die manuelle Suche nach Updates zu deaktivieren.`}:codexfastUpdateLocale.startsWith(`es`)?{label:`Desactivar actualizaciones automáticas`,description:`Detiene futuras comprobaciones e instalaciones automáticas sin desactivar la búsqueda manual.`}:codexfastUpdateLocale.startsWith(`pt`)?{label:`Desativar atualizações automáticas`,description:`Interrompe futuras verificações e instalações automáticas sem desativar a verificação manual.`}:codexfastUpdateLocale.startsWith(`it`)?{label:`Disattiva aggiornamenti automatici`,description:`Interrompe i futuri controlli e installazioni automatiche senza disattivare il controllo manuale.`}:codexfastUpdateLocale.startsWith(`ru`)?{label:`Отключить автоматические обновления`,description:`Останавливает последующие автоматические проверки и установки, не отключая ручную проверку.`}:{label:`Disable automatic updates`,description:`Stop future automatic update checks and installs without disabling manual Check for Updates.`};",
  "let codexfastUpdateChecked=codexfastDisableAutomaticUpdates??!1,codexfastUpdateOnChange;e[10]===t?codexfastUpdateOnChange=e[11]:(codexfastUpdateOnChange=e=>{B(t,j.disableAutomaticUpdates,e)},e[10]=t,e[11]=codexfastUpdateOnChange);let codexfastUpdateRow;return e[12]!==codexfastUpdateChecked||e[13]!==codexfastUpdateOnChange||e[14]!==codexfastUpdateMessages.label||e[15]!==codexfastUpdateMessages.description?(codexfastUpdateRow=(0,Z.jsx)(J,{label:codexfastUpdateMessages.label,description:codexfastUpdateMessages.description,control:(0,Z.jsx)(q,{checked:codexfastUpdateChecked,onChange:codexfastUpdateOnChange,ariaLabel:codexfastUpdateMessages.label})}),e[12]=codexfastUpdateChecked,e[13]=codexfastUpdateOnChange,e[14]=codexfastUpdateMessages.label,e[15]=codexfastUpdateMessages.description,e[16]=codexfastUpdateRow):codexfastUpdateRow=e[16],(0,Z.jsxs)(Z.Fragment,{children:[p,codexfastUpdateRow]})}",
].join("");
const GENERAL_SETTINGS_REPLACEMENT_26623 = (
  _match: string,
  functionName: string,
  cacheNamespace: string,
  settingsStateFunction: string,
  settingsStateArg: string,
  platformHook: string,
  intlHook: string,
  settingsRead: string,
  settingsNamespace: string,
  jsxNamespace: string,
  messageComponent: string,
  messagesNamespace: string,
  settingsWrite: string,
  rowComponent: string,
  toggleComponent: string,
): string =>
  [
    `function ${functionName}(){let codexfastCache=(0,${cacheNamespace}.c)(17),codexfastSettingsState=${settingsStateFunction}(${settingsStateArg}),{platform:codexfastPlatform}=${platformHook}(),codexfastIsSupportedPlatform=codexfastPlatform!==\`windows\`,codexfastIntl=${intlHook}(),codexfastPreventSleepValue=${settingsRead}(${settingsNamespace}.preventSleepWhileRunning),codexfastDisableAutomaticUpdates=${settingsRead}(${settingsNamespace}.disableAutomaticUpdates);if(!codexfastIsSupportedPlatform)return null;let codexfastPreventSleepLabel,codexfastPreventSleepDescription;codexfastCache[0]===Symbol.for(\`react.memo_cache_sentinel\`)?(codexfastPreventSleepLabel=(0,${jsxNamespace}.jsx)(${messageComponent},{...${messagesNamespace}.preventSleepWhileRunning}),codexfastPreventSleepDescription=(0,${jsxNamespace}.jsx)(${messageComponent},{id:\`settings.general.power.preventSleepWhileRunning.description\`,defaultMessage:\`Keep your computer awake while Codex is running a chat\`,description:\`Description for preventing sleep while a chat runs\`}),codexfastCache[0]=codexfastPreventSleepLabel,codexfastCache[1]=codexfastPreventSleepDescription):(codexfastPreventSleepLabel=codexfastCache[0],codexfastPreventSleepDescription=codexfastCache[1]);let codexfastPreventSleepChecked=codexfastPreventSleepValue??!1,codexfastPreventSleepOnChange;codexfastCache[2]===codexfastSettingsState?codexfastPreventSleepOnChange=codexfastCache[3]:(codexfastPreventSleepOnChange=codexfastNextValue=>{${settingsWrite}(codexfastSettingsState,${settingsNamespace}.preventSleepWhileRunning,codexfastNextValue)},codexfastCache[2]=codexfastSettingsState,codexfastCache[3]=codexfastPreventSleepOnChange);let codexfastPreventSleepAria;codexfastCache[4]===codexfastIntl?codexfastPreventSleepAria=codexfastCache[5]:(codexfastPreventSleepAria=codexfastIntl.formatMessage(${messagesNamespace}.preventSleepWhileRunning),codexfastCache[4]=codexfastIntl,codexfastCache[5]=codexfastPreventSleepAria);let codexfastPreventSleepRow;codexfastCache[6]!==codexfastPreventSleepChecked||codexfastCache[7]!==codexfastPreventSleepOnChange||codexfastCache[8]!==codexfastPreventSleepAria?(codexfastPreventSleepRow=(0,${jsxNamespace}.jsx)(${rowComponent},{label:codexfastPreventSleepLabel,description:codexfastPreventSleepDescription,control:(0,${jsxNamespace}.jsx)(${toggleComponent},{checked:codexfastPreventSleepChecked,onChange:codexfastPreventSleepOnChange,ariaLabel:codexfastPreventSleepAria})}),codexfastCache[6]=codexfastPreventSleepChecked,codexfastCache[7]=codexfastPreventSleepOnChange,codexfastCache[8]=codexfastPreventSleepAria,codexfastCache[9]=codexfastPreventSleepRow):codexfastPreventSleepRow=codexfastCache[9];`,
    "let codexfastUpdateLocale=(codexfastIntl.locale??globalThis.navigator?.language??``).toLowerCase(),codexfastUpdateMessages=codexfastUpdateLocale.startsWith(`zh-cn`)||codexfastUpdateLocale.startsWith(`zh-hans`)?{label:`停用自动更新`,description:`停止后续自动更新检查和安装，但不影响手动“检查更新”。`}:codexfastUpdateLocale.startsWith(`zh-tw`)||codexfastUpdateLocale.startsWith(`zh-hk`)||codexfastUpdateLocale.startsWith(`zh-hant`)?{label:`停用自動更新`,description:`停止後續自動更新檢查和安裝，但不影響手動「檢查更新」。`}:codexfastUpdateLocale.startsWith(`ja`)?{label:`自動更新を無効にする`,description:`今後の自動更新チェックとインストールを停止します。手動の「アップデートを確認」は無効になりません。`}:codexfastUpdateLocale.startsWith(`ko`)?{label:`자동 업데이트 비활성화`,description:`수동 업데이트 확인은 유지하면서 이후 자동 업데이트 확인 및 설치를 중지합니다.`}:codexfastUpdateLocale.startsWith(`fr`)?{label:`Désactiver les mises à jour automatiques`,description:`Arrête les prochaines recherches et installations automatiques sans désactiver la recherche manuelle.`}:codexfastUpdateLocale.startsWith(`de`)?{label:`Automatische Updates deaktivieren`,description:`Stoppt künftige automatische Prüfungen und Installationen, ohne die manuelle Suche nach Updates zu deaktivieren.`}:codexfastUpdateLocale.startsWith(`es`)?{label:`Desactivar actualizaciones automáticas`,description:`Detiene futuras comprobaciones e instalaciones automáticas sin desactivar la búsqueda manual.`}:codexfastUpdateLocale.startsWith(`pt`)?{label:`Desativar atualizações automáticas`,description:`Interrompe futuras verificações e instalações automáticas sem desativar a verificação manual.`}:codexfastUpdateLocale.startsWith(`it`)?{label:`Disattiva aggiornamenti automatici`,description:`Interrompe i futuri controlli e installazioni automatiche senza disattivare il controllo manuale.`}:codexfastUpdateLocale.startsWith(`ru`)?{label:`Отключить автоматические обновления`,description:`Останавливает последующие автоматические проверки и установки, не отключая ручную проверку.`}:{label:`Disable automatic updates`,description:`Stop future automatic update checks and installs without disabling manual Check for Updates.`};",
    `let codexfastUpdateChecked=codexfastDisableAutomaticUpdates??!1,codexfastUpdateOnChange;codexfastCache[10]===codexfastSettingsState?codexfastUpdateOnChange=codexfastCache[11]:(codexfastUpdateOnChange=codexfastNextValue=>{${settingsWrite}(codexfastSettingsState,${settingsNamespace}.disableAutomaticUpdates,codexfastNextValue)},codexfastCache[10]=codexfastSettingsState,codexfastCache[11]=codexfastUpdateOnChange);let codexfastUpdateRow;return codexfastCache[12]!==codexfastUpdateChecked||codexfastCache[13]!==codexfastUpdateOnChange||codexfastCache[14]!==codexfastUpdateMessages.label||codexfastCache[15]!==codexfastUpdateMessages.description?(codexfastUpdateRow=(0,${jsxNamespace}.jsx)(${rowComponent},{label:codexfastUpdateMessages.label,description:codexfastUpdateMessages.description,control:(0,${jsxNamespace}.jsx)(${toggleComponent},{checked:codexfastUpdateChecked,onChange:codexfastUpdateOnChange,ariaLabel:codexfastUpdateMessages.label})}),codexfastCache[12]=codexfastUpdateChecked,codexfastCache[13]=codexfastUpdateOnChange,codexfastCache[14]=codexfastUpdateMessages.label,codexfastCache[15]=codexfastUpdateMessages.description,codexfastCache[16]=codexfastUpdateRow):codexfastUpdateRow=codexfastCache[16],(0,${jsxNamespace}.jsxs)(${jsxNamespace}.Fragment,{children:[codexfastPreventSleepRow,codexfastUpdateRow]})}`,
  ].join("");
const GENERAL_SETTINGS_REPLACEMENT_26707_APP_NAME = (
  _match: string,
  functionName: string,
  cacheNamespace: string,
  settingsStateFunction: string,
  settingsStateArg: string,
  platformHook: string,
  intlHook: string,
  settingsRead: string,
  settingsNamespace: string,
  jsxNamespace: string,
  messageComponent: string,
  messagesNamespace: string,
  appNameValue: string,
  settingsWrite: string,
  rowComponent: string,
  toggleComponent: string,
): string =>
  [
    `function ${functionName}(){let codexfastCache=(0,${cacheNamespace}.c)(17),codexfastSettingsState=${settingsStateFunction}(${settingsStateArg}),{platform:codexfastPlatform}=${platformHook}(),codexfastIsSupportedPlatform=codexfastPlatform!==\`windows\`,codexfastIntl=${intlHook}(),codexfastPreventSleepValue=${settingsRead}(${settingsNamespace}.preventSleepWhileRunning),codexfastDisableAutomaticUpdates=${settingsRead}(${settingsNamespace}.disableAutomaticUpdates);if(!codexfastIsSupportedPlatform)return null;let codexfastPreventSleepLabel;codexfastCache[0]===Symbol.for(\`react.memo_cache_sentinel\`)?(codexfastPreventSleepLabel=(0,${jsxNamespace}.jsx)(${messageComponent},{...${messagesNamespace}.preventSleepWhileRunning}),codexfastCache[0]=codexfastPreventSleepLabel):codexfastPreventSleepLabel=codexfastCache[0];let codexfastPreventSleepDescription;codexfastCache[1]===Symbol.for(\`react.memo_cache_sentinel\`)?(codexfastPreventSleepDescription=(0,${jsxNamespace}.jsx)(${messageComponent},{id:\`settings.general.power.preventSleepWhileRunning.description\`,defaultMessage:\`Keep your computer awake while {appName} is running a task\`,description:\`Description for preventing sleep while a task runs\`,values:{appName:${appNameValue}}}),codexfastCache[1]=codexfastPreventSleepDescription):codexfastPreventSleepDescription=codexfastCache[1];let codexfastPreventSleepChecked=codexfastPreventSleepValue??!1,codexfastPreventSleepOnChange;codexfastCache[2]===codexfastSettingsState?codexfastPreventSleepOnChange=codexfastCache[3]:(codexfastPreventSleepOnChange=codexfastNextValue=>{${settingsWrite}(codexfastSettingsState,${settingsNamespace}.preventSleepWhileRunning,codexfastNextValue)},codexfastCache[2]=codexfastSettingsState,codexfastCache[3]=codexfastPreventSleepOnChange);let codexfastPreventSleepAria;codexfastCache[4]===codexfastIntl?codexfastPreventSleepAria=codexfastCache[5]:(codexfastPreventSleepAria=codexfastIntl.formatMessage(${messagesNamespace}.preventSleepWhileRunning),codexfastCache[4]=codexfastIntl,codexfastCache[5]=codexfastPreventSleepAria);let codexfastPreventSleepRow;codexfastCache[6]!==codexfastPreventSleepChecked||codexfastCache[7]!==codexfastPreventSleepOnChange||codexfastCache[8]!==codexfastPreventSleepAria?(codexfastPreventSleepRow=(0,${jsxNamespace}.jsx)(${rowComponent},{label:codexfastPreventSleepLabel,description:codexfastPreventSleepDescription,control:(0,${jsxNamespace}.jsx)(${toggleComponent},{checked:codexfastPreventSleepChecked,onChange:codexfastPreventSleepOnChange,ariaLabel:codexfastPreventSleepAria})}),codexfastCache[6]=codexfastPreventSleepChecked,codexfastCache[7]=codexfastPreventSleepOnChange,codexfastCache[8]=codexfastPreventSleepAria,codexfastCache[9]=codexfastPreventSleepRow):codexfastPreventSleepRow=codexfastCache[9];`,
    "let codexfastUpdateLocale=(codexfastIntl.locale??globalThis.navigator?.language??``).toLowerCase(),codexfastUpdateMessages=codexfastUpdateLocale.startsWith(`zh-cn`)||codexfastUpdateLocale.startsWith(`zh-hans`)?{label:`停用自动更新`,description:`停止后续自动更新检查和安装，但不影响手动“检查更新”。`}:codexfastUpdateLocale.startsWith(`zh-tw`)||codexfastUpdateLocale.startsWith(`zh-hk`)||codexfastUpdateLocale.startsWith(`zh-hant`)?{label:`停用自動更新`,description:`停止後續自動更新檢查和安裝，但不影響手動「檢查更新」。`}:codexfastUpdateLocale.startsWith(`ja`)?{label:`自動更新を無効にする`,description:`今後の自動更新チェックとインストールを停止します。手動の「アップデートを確認」は無効になりません。`}:codexfastUpdateLocale.startsWith(`ko`)?{label:`자동 업데이트 비활성화`,description:`수동 업데이트 확인은 유지하면서 이후 자동 업데이트 확인 및 설치를 중지합니다.`}:codexfastUpdateLocale.startsWith(`fr`)?{label:`Désactiver les mises à jour automatiques`,description:`Arrête les prochaines recherches et installations automatiques sans désactiver la recherche manuelle.`}:codexfastUpdateLocale.startsWith(`de`)?{label:`Automatische Updates deaktivieren`,description:`Stoppt künftige automatische Prüfungen und Installationen, ohne die manuelle Suche nach Updates zu deaktivieren.`}:codexfastUpdateLocale.startsWith(`es`)?{label:`Desactivar actualizaciones automáticas`,description:`Detiene futuras comprobaciones e instalaciones automáticas sin desactivar la búsqueda manual.`}:codexfastUpdateLocale.startsWith(`pt`)?{label:`Desativar atualizações automáticas`,description:`Interrompe futuras verificações e instalações automáticas sem desativar a verificação manual.`}:codexfastUpdateLocale.startsWith(`it`)?{label:`Disattiva aggiornamenti automatici`,description:`Interrompe i futuri controlli e installazioni automatiche senza disattivare il controllo manuale.`}:codexfastUpdateLocale.startsWith(`ru`)?{label:`Отключить автоматические обновления`,description:`Останавливает последующие автоматические проверки и установки, не отключая ручную проверку.`}:{label:`Disable automatic updates`,description:`Stop future automatic update checks and installs without disabling manual Check for Updates.`};",
    `let codexfastUpdateChecked=codexfastDisableAutomaticUpdates??!1,codexfastUpdateOnChange;codexfastCache[10]===codexfastSettingsState?codexfastUpdateOnChange=codexfastCache[11]:(codexfastUpdateOnChange=codexfastNextValue=>{${settingsWrite}(codexfastSettingsState,${settingsNamespace}.disableAutomaticUpdates,codexfastNextValue)},codexfastCache[10]=codexfastSettingsState,codexfastCache[11]=codexfastUpdateOnChange);let codexfastUpdateRow;return codexfastCache[12]!==codexfastUpdateChecked||codexfastCache[13]!==codexfastUpdateOnChange||codexfastCache[14]!==codexfastUpdateMessages.label||codexfastCache[15]!==codexfastUpdateMessages.description?(codexfastUpdateRow=(0,${jsxNamespace}.jsx)(${rowComponent},{label:codexfastUpdateMessages.label,description:codexfastUpdateMessages.description,control:(0,${jsxNamespace}.jsx)(${toggleComponent},{checked:codexfastUpdateChecked,onChange:codexfastUpdateOnChange,ariaLabel:codexfastUpdateMessages.label})}),codexfastCache[12]=codexfastUpdateChecked,codexfastCache[13]=codexfastUpdateOnChange,codexfastCache[14]=codexfastUpdateMessages.label,codexfastCache[15]=codexfastUpdateMessages.description,codexfastCache[16]=codexfastUpdateRow):codexfastUpdateRow=codexfastCache[16],(0,${jsxNamespace}.jsxs)(${jsxNamespace}.Fragment,{children:[codexfastPreventSleepRow,codexfastUpdateRow]})}`,
  ].join("");
export const UPDATE_TARGET_SPECS = defineTargetSpecs(
  {
    id: "disable-automatic-updates-schema",
    label: "Disable automatic updates schema",
    needle: SETTINGS_SCHEMA_NEEDLE,
    guardedSignature: SETTINGS_SCHEMA_GUARDED_SIGNATURE,
    patchedSignature: SETTINGS_SCHEMA_PATCHED_SIGNATURE,
    applyReplacement:
      "$1disableAutomaticUpdates:$2({agentAccess:`read-write`,default:!1,description:`Whether automatic update checks and forced installs are disabled`,key:`disableAutomaticUpdates`,schema:$3}),",
  },
  {
    id: "disable-automatic-updates-setting",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT,
  },
  {
    id: "disable-automatic-updates-setting-26623",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26623,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26623,
  },
  {
    id: "disable-automatic-updates-setting-26623-local-collision",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_LOCAL_COLLISION,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26623,
  },
  {
    id: "disable-automatic-updates-setting-26623-renamed-locals",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_RENAMED_LOCALS,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26623,
  },
  {
    id: "disable-automatic-updates-setting-26623-hooks",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26623_HOOKS,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26623,
  },
  {
    id: "disable-automatic-updates-setting-26707-app-name",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_APP_NAME,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26707_APP_NAME,
  },
  {
    id: "disable-automatic-updates-setting-26707-row-local-f",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_ROW_LOCAL_F,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26707_APP_NAME,
  },
  {
    id: "disable-automatic-updates-setting-26707-platform-locals",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_PLATFORM_LOCALS,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26707_APP_NAME,
  },
  {
    id: "disable-automatic-updates-setting-26707-shifted-locals",
    label: "Disable automatic updates setting",
    needle: GENERAL_SETTINGS_NEEDLE,
    guardedSignature: GENERAL_SETTINGS_GUARDED_SIGNATURE_26707_SHIFTED_LOCALS,
    patchedSignature: GENERAL_SETTINGS_PATCHED_SIGNATURE_26623,
    applyReplacement: GENERAL_SETTINGS_REPLACEMENT_26707_APP_NAME,
  },
);
